design:
  theme: modern
  page:
    size: us-letter
    top_margin: 2cm
    bottom_margin: 2cm
    left_margin: 2cm
    right_margin: 2cm
    show_page_numbering: false
    show_last_updated_date: false
  colors:
    text: rgb(40, 40, 40)
    name: rgb(20, 20, 20)
    connections: rgb(0, 150, 136)         # teal accent
    section_titles: rgb(0, 150, 136)
    links: rgb(0, 120, 200)
    last_updated_date_and_page_numbering: rgb(120, 120, 120)
  text:
    font_family: Inter
    font_size: 9pt
    leading: 1.4em
    alignment: left
    date_and_location_column_alignment: right
  links:
    underline: false
    use_external_link_icon: false
  header:
    name_font_family: Inter
    name_font_size: 32pt
    name_bold: true
    photo_width: 3cm
    vertical_space_between_name_and_connections: 0.5cm
    vertical_space_between_connections_and_first_section: 0.8cm
    horizontal_space_between_connections: 0.6cm
    connections_font_family: Inter
    separator_between_connections: "•"
    use_icons_for_connections: true
    alignment: left
  section_titles:
    type: with-full-line
    font_family: Inter
    font_size: 1.6em
    bold: true
    small_caps: false
    line_thickness: 1pt
    vertical_space_above: 0.8cm
    vertical_space_below: 0.4cm
  entries:
    date_and_location_width: 4cm
    left_and_right_margin: 0.2cm
    horizontal_space_between_columns: 0.3cm
    vertical_space_between_entries: 1.4em
    allow_page_break_in_sections: true
    allow_page_break_in_entries: true
    short_second_row: false
    show_time_spans_in: []
  highlights:
    bullet: "–"
    top_margin: 0.2cm
    left_margin: 0.5cm
    vertical_space_between_highlights: 0.25cm
    horizontal_space_between_bullet_and_highlight: 0.6em
    summary_left_margin: 0cm
  entry_types:
    one_line_entry:
      template: '**LABEL:** DETAILS'
    education_entry:
      main_column_first_row_template: '**INSTITUTION** – AREA'
      degree_column_template: '**DEGREE**'
      degree_column_width: 1.2cm
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: |-
        LOCATION
        DATE
    normal_entry:
      main_column_first_row_template: '**NAME**'
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: |-
        LOCATION
        DATE
    experience_entry:
      main_column_first_row_template: '**POSITION**, **COMPANY**'
      main_column_second_row_template: |-
        SUMMARY
        HIGHLIGHTS
      date_and_location_column_template: |-
        LOCATION
        DATE
    publication_entry:
      main_column_first_row_template: '**TITLE**'
      main_column_second_row_template: |-
        AUTHORS
        URL (JOURNAL)
      main_column_second_row_without_journal_template: |-
        AUTHORS
        URL
      main_column_second_row_without_url_template: |-
        AUTHORS
        JOURNAL
      date_and_location_column_template: DATE
locale:
  language: en
  phone_number_format: national
  page_numbering_template: NAME – PAGE_NUMBER / TOTAL_PAGES
  last_updated_date_template: Last updated on TODAY
  date_template: MONTH YEAR
  month: month
  months: months
  year: year
  years: years
  present: Present
  to: "–"
  abbreviations_for_months:
    - Jan
    - Feb
    - Mar
    - Apr
    - May
    - Jun
    - Jul
    - Aug
    - Sep
    - Oct
    - Nov
    - Dec
  full_names_of_months:
    - January
    - February
    - March
    - April
    - May
    - June
    - July
    - August
    - September
    - October
    - November
    - December
rendercv_settings:
  date: '2025-08-27'
  render_command:
  bold_keywords: ["Python", "AI", "ML", "Leadership"]
